### ISSUE TITLE
MigratorWordpress import fails

### ISSUE THREAD

**Issue by phlppschrr** [adrianbj/ProcessMigrator#4]
I am trying to import a wordpress-xml file with MigratorWordpress. The fields and templates are created successfully, but no pages are imported/created. 
If using a 'Import Type' of  'Append' the import silently fails, when using 'Overwrite' or 'Replace' I get this error:
Error: Uncaught Error: Call to a member function get() on null in /xxx/site/modules/ProcessMigrator/ProcessMigrator.module:1450

Tested on fresh PW 2.7.3 and 3.0.16 with PHP7.

**Comment by adrianbj** [comment]
Sorry, I don't have much time for this module at the moment, but I know for certain that Wordpress migrations were working. I made a couple of fairly recent commits to this that I think may have broken some things. I do hope to revisit shortly. In the meantime, could you please try this commit: https://github.com/adrianbj/ProcessMigrator/tree/3e2121b8fdb68e9d9dc0c6aca8aae75e923a2669

I am pretty sure that should still work for WP migrations.

**Comment by phlppschrr** [comment]
Wow, thanks for the prompt answer. This version seems to work fine!

**Comment by adrianbj** [comment]
No problem - thanks for confirming that version works. I will try to make some time shortly to redo the attempted fixes in the two versions since that one.

**Comment by adrianbj** [comment]
Lates commit should fix the Wordpress import issues, so please use that one from now on.
